version: '3.7'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: huggingface-models-server
    ports:
      - "8888:80"
    volumes:
      - ./server:/app/server
      - ./data:/app/data
      - ./tasks:/app/tasks
      - ./entrypoint.sh:/app/entrypoint.sh
      - ./server/conf/app.conf:/etc/nginx/conf.d/app.conf
      - ./server/conf/proxy.conf:/etc/nginx/proxy.conf
      - ./server/conf/nginx.conf:/etc/nginx/nginx.conf
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
              